name: R-UNet

data_config:
  dataset_dir: E:/GLX/Projects/Aneurysm/S/one

train_config:
  epochs: 100
  batch_size: 6
  output_dir: logs
  num_workers: 4
  buffer_size: 8

net_config:
  classes: 2
  learning_rate: 0.001
  slice_window_roi: [192, 192, 64]

seed: 1228
