name: R-UNet

data_config:
  dataset_dir: E:/GLX/Projects/Aneurysm/S/one

train_config:
  epochs: 300
  batch_size: 6
  output_dir: logs

net_config:
  classes: 2  # labels classes
  learning_rate: 0.001
  slice_window_roi: [ 192, 192, 64 ]

seed: 1228
