name: Spleen

data_config:
  dataset_dir: E:/GLX/Datasets/Task09_Spleen/imagesTr

train_config:
  epochs: 100
  batch_size: 6
  output_dir: logs
  num_workers: 8
  buffer_size: 12

net_config:
  classes: 2
  learning_rate: 0.001
  slice_window_roi: [192, 192, 64]

seed: 1228
